### ISSUE TITLE
Direct ant can to ve can

### ISSUE THREAD

**Issue by pahorpet** [JuWorkshop/AntBms-to-Ve.Can-Victron-Venus#1]
Hi great project but still need an extra piece of hw. But easier than installing sw in cerbo,...
I will try to test and support as well.

I had ask an dealer of ant directly and they are allowed to update their can based on venusos specification if I can supply the communication protocol. Maybe this could be also a way?

**Comment by JuWorkshop** [comment]
Hi, thanks for the feedback.
Indeed, it is a good initiative if ant directly integrates the protocol.
I haven't yet found all the registers
This is functional, and seems common to several manufacturers (pylontech, rec, ect):
11-bit TX identifiers: 0x351, 0x355, 0x356, 0x35A, 0x35B, 0x35E, 0x370
8 byte message structure
CAN messages are sent each measuring cycle with 150 | 250 ms interval.

**Comment by pahorpet** [comment]
Do you have a detailed CAN protocol?  I would like to give it a try but need to be done with all history status and so on as I had tested on USB communication.

[simp-bms-setup-manual-v025.pdf](https://github.com/JuWorkshop/AntBms-to-Ve.Can-Victron-Venus/files/7332142/simp-bms-setup-manual-v025.pdf)

**Comment by JuWorkshop** [comment]
[vecan-registers-public.pdf](https://github.com/JuWorkshop/AntBms-to-Ve.Can-Victron-Venus/files/7370537/vecan-registers-public.pdf)
