### ISSUE TITLE
Connection and commissioning

### ISSUE THREAD

**Issue by moto600** [JuWorkshop/AntBms-to-Ve.Can-Victron-Venus#2]
great project. I can't quite get along with the information. how exactly is the connection between your control unit and the CerboGX? the hdr-f-2.45 has 3 connections but Ve.Can has 4 connections. what exactly do you do with the Src_Teensy3.2AntBmsToCan.ino?

thx

**Comment by JuWorkshop** [comment]
just connect GND, CAN HI, CAN LO on GX.
Teensy.ino read rs232 bms serial port and write data on another serial port used as CAN.
Teensy do  protocol conversion from rs232 to CAN format.

**Comment by moto600** [comment]
but ve.can has 4 pins. what of it is what

**Comment by moto600** [comment]
![33995BC0-B563-42C8-B944-48E2EC15DD63](https://user-images.githubusercontent.com/91275236/134775142-2a3e5964-a330-47a3-ab2a-c7c0adb374d9.png)

found that ... what is can hi and what can lo

**Comment by moto600** [comment]
and does this Teensy 3.2 need a power supply or does it work like that?

**Comment by moto600** [comment]
in the plan is 1k ohm resistance and a capacitor of 0.1y ... in the description is what a 120 ohm resistance! what now? och please for feedback ... have all the components ... would like to try it out

**Comment by JuWorkshop** [comment]
> ![33995BC0-B563-42C8-B944-48E2EC15DD63](https://user-images.githubusercontent.com/91275236/134775142-2a3e5964-a330-47a3-ab2a-c7c0adb374d9.png)
> 

Not a Ve.can port, this pict, = Ve.direct port rs232 (mppt?).

**Comment by moto600** [comment]
![3D113129-5449-4582-970C-D49EB9E5C9E9](https://user-images.githubusercontent.com/91275236/134798651-392bcb93-bc23-4e97-aa12-3e0d6bc453fe.gif)

okay my mistake. so this here. what about the resistance 1k ohn and that 0,1y
capacitor?

**Comment by JuWorkshop** [comment]
I must correctly complete the schematic.
Teensy is powered by vcc bms-port. ( Vin "teensy" connected to Vcc from Bms port).
 pin3 "sn65hd233" connected to 3.3volt teensy pin.

GX device has 2 can ports, (1 opto-isolated and 1 non isolat).
-opto isolate require gnd, H, L and Vcc (from sn65hdv233).
non isolate only require gnd, H, L.

120 ohm, is can bus terminal:
![image](https://user-images.githubusercontent.com/89390048/134798678-e81e6bf2-7fd3-48ad-b4b5-a133aa4bf0c6.png)

accordind iso 11898: https://en.wikipedia.org/wiki/CAN_bus#CAN_lower-layer_standards

**Comment by moto600** [comment]
![Uploading C516BDCA-3FFF-4554-A413-4E74F5D6C2F1.jpeg…]()
is that so correct

**Comment by moto600** [comment]
![9E576FFF-344F-4EFE-8D1E-69CC41916370](https://user-images.githubusercontent.com/91275236/134800893-b601f27d-8c61-4748-8825-f69fbdceb419.jpeg)

**Comment by moto600** [comment]
is that so correct

![D113D1C4-DD67-40CF-8FDC-D9368C6CA892](https://user-images.githubusercontent.com/91275236/134801251-97ffc340-dc72-4c46-b024-04e9c5b40fb0.jpeg)

**Comment by JuWorkshop** [comment]
> is that so correct
> 
> ![D113D1C4-DD67-40CF-8FDC-D9368C6CA892](https://user-images.githubusercontent.com/91275236/134801251-97ffc340-dc72-4c46-b024-04e9c5b40fb0.jpeg)

Correct, I run like this. With gnd line : antBms port gnd // teensy gnd.

**Comment by JuWorkshop** [comment]
![0_Teensy3,2_vecan_sch_rect](https://user-images.githubusercontent.com/89390048/134801421-5c7fc04c-47f9-45d3-baee-a4fe5676cbd4.png)

**Comment by moto600** [comment]
Hello. have ordered the SN65HVD230. as can be seen in the photo, there are other connections here. does it work anyway? how do you have to set the 1K resistance and the capacitor?

In addition, it has completely different connections D and R are not available either ...
the module SN65HDV233 is not available anywhere ...

is there any information about the pin assignment of the ant-bms?

![4B0943F1-B33D-4A21-B4D2-00034CD7F6C3](https://user-images.githubusercontent.com/91275236/134886790-dca53e7b-5d0e-4165-b17d-123adb50116a.png)

**Comment by moto600** [comment]
have now asked some dealers in china. they all say the module SN65HDV233 would not exist

**Comment by JuWorkshop** [comment]
[SN65HVD233DRG4 .pdf](https://github.com/JuWorkshop/AntBms-to-Ve.Can-Victron-Venus/files/7329674/SN65HVD233DRG4.pdf)

**Comment by JuWorkshop** [comment]
http://www.ti.com/general/docs/suppproductinfo.tsp?distId=26&gotoUrl=http%3A%2F%2Fwww.ti.com%2Flit%2Fgpn%2Fsn65hvd233

**Comment by moto600** [comment]
good and where can I buy it

**Comment by JuWorkshop** [comment]
https://fr.farnell.com/search?st=sn65hvd233

**Comment by pahorpet** [comment]
Hi 
1. do you have a layout for isolated input I am not able to run it. only nonisolated 
2. I don't see the battery in the cerbo and I have 25% errors on RX packets and TX all of them are dropped. 
3. I am using MCP2515 can it be the issue?

**Comment by JuWorkshop** [comment]
Hi,
I' use Si8422 for isolated ve-can line. With Ant bms it's work same with opto isolated and non opto-isolated.
![Capture d’écran de 2021-11-20 08-07-09](https://user-images.githubusercontent.com/89390048/142718013-669015aa-bf39-475b-83b7-e99a5c4925c1.png)

**Comment by pahorpet** [comment]
And layout of Rj45? It is only 1,2,3(H,L,Gnd)? 
Any idea what can be wrong at second question?
Have you been working on another version?

**Comment by JuWorkshop** [comment]
No forgetting 120 Ohm CAN bus terminator (H//L)? config cerbo can 500kbit?
I use home made cape for beagleboneblack as cerbo:
![DSC_0514](https://user-images.githubusercontent.com/89390048/142753073-e1b75966-242c-45de-a0b5-ce00a519b4e0.jpg)
![DSC_0492](https://user-images.githubusercontent.com/89390048/142753084-25a5ddba-6bd8-40b1-8dd4-53fef80d215f.jpg)
![DSC_0465](https://user-images.githubusercontent.com/89390048/142753103-3793d825-db0f-4ae4-83f4-688e77206bd9.jpg)
![DSC_0461](https://user-images.githubusercontent.com/89390048/142753116-8a0f2b5c-d73d-4b39-aad1-c603a0d20ef0.jpg)

**Comment by pahorpet** [comment]
No forgetting 120 Ohm CAN bus terminator (H//L)? using original on at cerbo and can module already have it there
 config cerbo can 500kbit? sure

**Comment by JuWorkshop** [comment]
120 Ohm on  bms canH//canL.
Yes 500kbit or need change source code line 11:
int  canSpeed = 500; // kbit/s
config cerbo ect:
https://github.com/JuWorkshop/AntBms-to-Ve.Can-Victron-Venus/wiki
